"""Helper scripts for debazel build rules."""

package(default_visibility = ["//:internal"])

filegroup(
    name = "binary_package",
    srcs = ["binary_package.sh"],
)

filegroup(
    name = "files_to_install",
    srcs = glob(["**"]),
)
